server:
  port: 2101
spring:
  application:
    name: eureka-consumer-ribbon

eureka:
  instance:
    hostname: localhost
    instance-id: eureka-consumer-ribbon # \u5FAE\u670D\u52A1\u522B\u540D
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/