server:
  port: 2001
eureka:
  instance:
    hostname: localhost
    instance-id: eureka-client1 # \u5FAE\u670D\u52A1\u522B\u540D
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/ # \u6307\u660E\u6CE8\u518C\u4E2D\u5FC3\u7684\u4F4D\u7F6E
spring:
  application:
    name: eureka-client # \u4F7F\u7528\u8BE5\u540D\u79F0\u4F5C\u4E3A\u5FAE\u670D\u52A1\u8C03\u7528

#  cloud:
#    consul: # \u53E6\u4E00\u79CD\u670D\u52A1\u6CBB\u7406\u5B9E\u73B0\u6846\u67B6
#      host: localhost
#      port: 8500

